const images = [
    { id: 1, src: '/characters/Lili.png', name: 'Lili' },
    { id: 2, src: '/characters/Alisa.png', name: 'Alisa' },
    { id: 3, src: '/characters/Asuka.png', name: 'Asuka' },
    { id: 4, src: '/characters/Azucena.png', name: 'Azucena' },
    { id: 5, src: '/characters/Bryan-Fury.png', name: 'Bryan Fury' },
    { id: 6, src: '/characters/Claudio-Serafino.png', name: 'Claudio Serafino' },
    { id: 7, src: '/characters/Devil-Jin.png', name: 'Devil Jin' },
    { id: 8, src: '/characters/Feng-Wei.png', name: 'Feng Wei' },
    { id: 9, src: '/characters/Hwoarang.png', name: 'Hwoarang' },
    { id: 10, src: '/characters/Jack-8.png', name: 'Jack 8' },
    { id: 11, src: '/characters/Jin.png', name: 'Jin' },
    { id: 12, src: '/characters/Jun-Kazama.png', name: 'Jun Kazama' },
    { id: 13, src: '/characters/Kazuya-Mishima.png', name: 'Kazuya Mishima' },
    { id: 14, src: '/characters/King.png', name: 'King' },
    { id: 15, src: '/characters/Kuma.png', name: 'Kuma' },
    { id: 16, src: '/characters/Lars-Alexandersson.png', name: 'Lars Alexandersson' },
    { id: 17, src: '/characters/Lee.png', name: 'Lee' },
    { id: 18, src: '/characters/Leo.png', name: 'Leo' },
    { id: 19, src: '/characters/Leroy-Smith.png', name: 'Leroy Smith' },
    { id: 20, src: '/characters/Ling-Xiaoyu.png', name: 'Ling Xiaoyu' },
    { id: 21, src: '/characters/Marshall-Law.png', name: 'Marshall Law' },
    { id: 22, src: '/characters/Nina-Williams.png', name: 'Nina Williams' },
    { id: 23, src: '/characters/Panda.png', name: 'Panda' },
    { id: 24, src: '/characters/Paul-Phoenix.png', name: 'Paul Phoenix' },
    { id: 25, src: '/characters/Raven.png', name: 'Raven' },
    { id: 26, src: '/characters/Reina.png', name: 'Reina' },
    { id: 27, src: '/characters/Sergei-Dragunov.png', name: 'Sergei Dragunov' },
    { id: 28, src: '/characters/Shaheen.png', name: 'Shaheen' },
    { id: 29, src: '/characters/Steve-Fox.png', name: 'Steve Fox' },
    { id: 30, src: '/characters/Victor-Chevalier.png', name: 'Victor Chevalier' },
    { id: 31, src: '/characters/Yoshimitsu.png', name: 'Yoshimitsu' },
    { id: 32, src: '/characters/Zafina.png', name: 'Zafina' },
  ];
  
  export default images;
  